title: Antonio Di Giovanni # your name (or website title) here
logo: "/images/profile_circle.png?raw=true" # your photo (or logo) here
url: "https://antoniodigiovanni.com"  # Your custom domain
baseurl: ""  # Leave empty for custom domains

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  XXX.
  <br><br>
  XXX
  <br><br>
  <a href="https://www.linkedin.com/in/antonio-di-giovanni/">LinkedIn Profile</a> 
  <a href="https://github.com/Antoniodigiovanni">GitHub Profile</a> 
  <a href="pdf/antonio_di_giovanni, cv.pdf?raw=true)">CV</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-RLJJ9SNHJN # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
