title: Antonio Di Giovanni # your name (or website title) here
logo: "/images/profile_circle.png?raw=true" # your photo (or logo) here
url: "https://antoniodigiovanni.com"  # Your custom domain
baseurl: ""  # Leave empty for custom domains

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data scientist with a strong focus on 
  time series forecasting, tabular data and deep learning.
  <br>
  
  Previous experiences include roles in startups, investment firms, and a leading strategy consulting firm, combining technical depth with business-oriented problem solving.

  <br><br>
  <a href="https://www.linkedin.com/in/antonio-di-giovanni/", target="_blank" rel="noopener noreferrer">LinkedIn Profile</a> <br>
  <a href="https://github.com/Antoniodigiovanni", target="_blank" rel="noopener noreferrer">GitHub Profile</a> <br>
  <a href="pdf/antonio_di_giovanni, cv.pdf?raw=true", target="_blank" rel="noopener noreferrer">CV</a> <br>
  
theme: jekyll-theme-minimal
google_analytics: G-RLJJ9SNHJN # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
